sudo: required
language: python
python:
  - "2.7"
os:
  - linux
before_install:
  - sudo apt-get install python-dev
install: "pip install -r requirements.txt"
before_script:
  - python --version
script: nosetests
notifications:
  email:
    on_success: never
